# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da19447e469ad7b6cc20359183494906e4bfe337e84ffd7aacb3aaaf62ad04cd95720b88d10a025cfd80b23ac14b0b93e5ded9a6328eaad7ea8326dc1b461495

test:
  secret_key_base: 7e48fc134859b7f52d92b76cbe6da4b8849afa48fbbd8d0ea7ef75660cbdf5e01d9c232adfdefc618935f4fe6de3c423e9275338fa0dfc20b060e5da15b775ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
