# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a577a79030ea6a90598314a50578524da47e316bc928d4de300fd4796a1a5daba5a912ed661ec8613e38cc19aad039b773ab7dc71df5450d6d9ab6165ab3ea0

test:
  secret_key_base: c6e380e33009df350f69e4eeea760be376ebb7a9a2723740d7617e7c1fce406d096ffc4934c58dd02112b90232c5485af3a9312251cde9a76484849ff1a2aa8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
